server:
  port: 8080
  servlet:
    application-display-name: Spring-Kafka Demo
    context-path: /kafka
spring:
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: group-todo
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: "*"
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
kafka:
  topic: todo-topic
